controllers:
    resource: ../src/Controller/
    type: attribute

open:
    path: /
    controller: App\Controller\indexController::open

drole:
    path: /test
    controller: App\Controller\indexController::drole

connexion:
    path: /connexion
    controller: App\Controller\indexController::connexion

importer:
    path: /importer/{verif}
    controller: App\Controller\indexController::importer