controllers:
    resource: ../src/Controller/
    type: attribute

open:
    path: /
    controller: App\Controller\indexController::open

album:
    path: /repertoireAlbum
    controller: App\Controller\indexController::album

connexion:
    path: /connexion
    controller: App\Controller\indexController::connexion

importer:
    path: /importer/{verif}
    controller: App\Controller\indexController::importer