controllers:
    resource: ../src/Controller/
    type: attribute

open:
    path: /
    controller: App\Controller\indexController::open

drole:
    path: /drole
    controller: App\Controller\indexController::drole